// Copyright (c) 2026 SPHARX Ltd. All Rights Reserved.
//
// Template content for CLI scaffolding commands.
// These are the default files generated by agentrt init and agentrt create.

/// Default agentos.yaml configuration template.
pub const DEFAULT_AGENTOS_YAML: &str = r#"# AgentRT Project Configuration
# Generated by: agentrt init

kernel:
  name: "AgentRT-Core"
  version: "0.1.1"

llm:
  providers:
    openai:
      api_key: "${OPENAI_API_KEY}"
      models:
        - "gpt-4o"
        - "gpt-4o-mini"
      default_model: "gpt-4o-mini"
      temperature: 0.7
      max_tokens: 4096
    local:
      api_key: ""
      models:
        - "local"
      default_model: "local"
      temperature: 0.7
      max_tokens: 4096

security:
  enabled: true
  mode: "standard"

hooks:
  enabled: true
  global_hooks:
    on_agent_start:
      - hook: "security_reminder"
        priority: 90
        config:
          security_level: "standard"

observability:
  metrics:
    enabled: true
  logging:
    level: "info"
    format: "text"
"#;

/// Default agent definition.
pub const DEFAULT_AGENT_YAML: &str = r#"# Agent Definition
name: "main-agent"
version: "0.1.0"
description: "Default AgentRT agent"

system_prompt: "prompts/system.yaml"
model: "gpt-4o-mini"

tools:
  - "tools/custom.py"

hooks:
  - "hooks/audit.py"

memory:
  enabled: true
  max_context_tokens: 8192

max_turns: 20
temperature: 0.7
"#;

/// Default system prompt template.
pub const DEFAULT_SYSTEM_PROMPT: &str = r#"# System Prompt
# This prompt is sent to the LLM at the beginning of each conversation.

role: "system"
template: |
  You are a helpful AI assistant running on the AgentRT platform.

  When responding:
  - Be concise and accurate
  - Use tools when appropriate to gather information
  - If you are unsure, say so
  - Follow the user's instructions carefully

  Current context:
  - Date: {date}
  - Session: {session_id}
"#;

/// Example custom tool.
pub const EXAMPLE_TOOL: &str = r#"# Copyright (c) 2026 SPHARX Ltd. All Rights Reserved.
"""
Custom Tool for AgentRT

Implement the execute() function to define your tool's behavior.
Tools are called by the agent during task execution.
"""

from typing import Any, Dict


def get_metadata() -> Dict[str, Any]:
    """Return tool metadata for registration."""
    return {
        "name": "custom_tool",
        "description": "A custom tool for AgentRT",
        "version": "0.1.0",
        "parameters": {
            "input": {
                "type": "string",
                "description": "Input data for the tool",
                "required": True,
            },
        },
    }


def execute(params: Dict[str, Any]) -> Dict[str, Any]:
    """Execute the tool with the given parameters.

    Args:
        params: Tool parameters from the agent.

    Returns:
        Dict with 'result' key containing the output.
    """
    input_data = params.get("input", "")

    # TODO: Implement your tool logic here

    return {
        "result": f"Processed: {input_data}",
        "status": "success",
    }
"#;

/// Example hook.
pub const EXAMPLE_HOOK: &str = r#"# Copyright (c) 2026 SPHARX Ltd. All Rights Reserved.
"""
Custom Hook for AgentRT

Hooks intercept agent lifecycle events.
This example logs all tool calls to the console.
"""

from ecosystem.hooks import BaseHook, HookContext, HookResult


class CustomAuditHook(BaseHook):
    name = "custom_audit"
    version = "0.1.0"
    priority = 50

    def on_tool_call(self, ctx: HookContext, tool_name: str = "", tool_input: Any = None) -> HookResult:
        print(f"[HOOK] Tool called: {tool_name} by agent {ctx.agent_id}")
        return HookResult(allowed=True)

    def on_tool_result(self, ctx: HookContext, tool_name: str = "", result: Any = None) -> HookResult:
        print(f"[HOOK] Tool result: {tool_name} -> {str(result)[:100]}")
        return HookResult(allowed=True)
"#;

/// Example plugin.
pub const EXAMPLE_PLUGIN: &str = r#"# Copyright (c) 2026 SPHARX Ltd. All Rights Reserved.
"""
Example Plugin for AgentRT

Plugins extend the AgentRT runtime with custom functionality.
They follow a lifecycle: init -> start -> stop -> destroy.
"""

from typing import Any, Dict


class MyPlugin:
    """Example plugin implementation."""

    def __init__(self):
        self._running = False

    def init(self, config: Dict[str, Any]) -> bool:
        """Initialize the plugin with configuration."""
        print(f"[PLUGIN] Initializing with config: {config}")
        return True

    def start(self) -> bool:
        """Start the plugin."""
        self._running = True
        print("[PLUGIN] Started")
        return True

    def stop(self) -> bool:
        """Stop the plugin."""
        self._running = False
        print("[PLUGIN] Stopped")
        return True

    def destroy(self) -> bool:
        """Clean up plugin resources."""
        print("[PLUGIN] Destroyed")
        return True

    def is_running(self) -> bool:
        """Check if the plugin is running."""
        return self._running
"#;

/// Example Prompt template.
pub const EXAMPLE_PROMPT: &str = r#"# Prompt Template: example-prompt
# Generated by: agentrt create prompt

name: "example-prompt"
version: "0.1.0"
description: "An example prompt template"

role: "system"
template: |
  You are a helpful assistant.

  Instructions:
  {instructions}

  Context:
  {context}
"#;

/// Example Skill.
pub const EXAMPLE_SKILL: &str = r#"# Skill: example-skill
# Generated by: agentrt create skill

## Metadata
- **Name:** example-skill
- **Version:** 0.1.0
- **Category:** general

## Description
An example skill that demonstrates the skill definition format.

## Instructions
When this skill is activated, follow these guidelines:

1. Understand the user's request thoroughly
2. Break down complex tasks into manageable steps
3. Use tools when appropriate to gather information
4. Provide clear, actionable results

## Examples

### Example 1: Basic Task
**User:** "Analyze this data"
**Response:** Use data analysis tools to process the input, then summarize findings.

### Example 2: Complex Task
**User:** "Build a report"
**Response:** Break down into steps: gather data → analyze → format → present.
"#;

/// .gitignore template.
pub const GITIGNORE: &str = r#"# AgentRT Project - .gitignore

# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/

# Environment
.env
.env.local
*.local.yaml

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# AgentRT
/var/
*.log
"#;